version: 2

jobs:
  build:
    docker:
      - image: node:12
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run lint
